version: '3.9'

services:
  app:
    build:
      context: ./docker/php
    container_name: online-library-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: ["symfony", "server:start", "--no-tls", "--allow-http", "--port=8000"]

  postgres:
    image: postgres:15
    container_name: online-library-db
    environment:
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: library_pass
      POSTGRES_DB: library_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: